---
driver:
  name: vagrant
  # without additional memory, ubuntu suites will fail
  customize:
    memory: 1024

provisioner:
  name: chef_solo
  attributes:
    cassandra:
      cluster_name: test

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.4
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[cassandra::default]

  - name: tarball
    run_list:
      - recipe[cassandra::tarball]

  - name: dse
    run_list:
      - recipe[cassandra::default]
    attributes:
      cassandra:
        dse:
          credentials:
            databag: false
            username: <%= ENV['CASSANDRA_DSE_USERNAME'] %>
            password: <%= ENV['CASSANDRA_DSE_PASSWORD'] %>
